### ISSUE TITLE
Users can edit posts that they didn't make

### ISSUE THREAD

**Issue by talm-quest** [lillian-gardenia-seabreeze/msgboard#8]

**Comment by lillian-gardenia-seabreeze** [comment]
This *should* be the concerning line but looks right. I'll have to test this...

https://github.com/lillian-gardenia-seabreeze/msgboard/blob/master/api/msgboard.py#L129

**Comment by lillian-gardenia-seabreeze** [comment]
Only for your branch which is out of date, please close issue to confirm.

**Comment by talm-quest** [comment]
lol
